version: '3.4'

services:

#REACT FRONT-END SERVICE

  angular.app:
    container_name: angular.app
    image: ${DOCKER_REGISTRY-}bookhistoryapp
    build:
      context: .
      dockerfile: BookHistory.App/ClientApp/Dockerfile
    ports:
      - "4200:4200" 
      - "49153:49153"
    restart: on-failure
    volumes:
      - ./BookHistory.App/ClientApp:/app

#BACK-END SERVICES

  bookhistory.app:
    container_name: book.history.api
    image: ${DOCKER_REGISTRY-}bookhistoryapp
    build:
      context: .
      dockerfile: BookHistory.App/Dockerfile
      args:
        - skip_client_build=true

#DATABASES

  postgre.server:
    container_name: postgre.book.history.srv
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - postgresql-db:/var/lib/postgresql/data

#TOOLS

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./src/Tributech.DataSpace.DB/pgadmin_servers.json:/pgadmin4/servers.json

volumes:
  postgresql-db: